// <auto-generated />
using System;
using Descontos.Admin.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Descontos.Admin.API.Migrations
{
    [DbContext(typeof(DescontosAdminAPIContext))]
    [Migration("20220913194910_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Descontos.Admin.API.Models.Desconto", b =>
                {
                    b.Property<int>("DescontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescontoId"), 1L, 1);

                    b.Property<DateTime>("DataEHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDePagamento")
                        .HasColumnType("int");

                    b.HasKey("DescontoId");

                    b.ToTable("Desconto");
                });
#pragma warning restore 612, 618
        }
    }
}
